### PR TITLE
Save Exif rotation tag for resized version

### LINKED ISSUE #20: Exif issue
Code :
```
            mCameraImagePicker = new CameraImagePicker(activity);
            mCameraImagePicker.shouldGenerateMetadata(true);
            mCameraImagePicker.shouldGenerateThumbnails(false);
            mCameraImagePicker.ensureMaxSize(1920, 1920);
            mCameraImagePicker.setImagePickerCallback(this);
```

This line in particular :
```
            mCameraImagePicker.ensureMaxSize(1920, 1920);
```
has an issue : I think it doesn't copy the exif params into the reiszed file.  All your resized file don't have exif (or change orientation before saving).
So, Glide can't orientate it correctly

To help : http://stackoverflow.com/questions/13596500/android-image-resizing-and-preserving-exif-data-orientation-rotation-etc

We also do something which can help you : 
``` 
public static Bitmap getResizedBitmap(Bitmap bm, int newWidth, int newHeight) {
        int width = bm.getWidth();
        int height = bm.getHeight();
        float scaleWidth = ((float) newWidth) / width;
        float scaleHeight = ((float) newHeight) / height;
        // CREATE A MATRIX FOR THE MANIPULATION
        Matrix matrix = new Matrix();
        // RESIZE THE BIT MAP
        matrix.postScale(scaleWidth, scaleHeight);

        // RECREATE THE NEW BITMAP
        Bitmap resizedBitmap;
        try {
            resizedBitmap = Bitmap.createBitmap(
                    bm, 0, 0, width, height, matrix, false);
        } catch (OutOfMemoryError error) {
            // do something
        }
        return resizedBitmap;
    }```

### PR DESCRIPTION
**Pull request by xHunter**
Fix #20

### CODE REVIEW

**Comment by CorentinPacaud** [comment]
So can you update the Master branch now ? because it has been fix in Dev but we can't access the update from gradle. Thx.

**Comment by coomar2841** [comment]
Done.

**Comment by CorentinPacaud** [comment]
Hmmm, how can we have access to the new update ?

**Comment by coomar2841** [comment]
Will release a new build today.

**Comment by CorentinPacaud** [comment]
Well, after testing, the new version doesn't work. With Sony devices (XPeria Z for me), it doesn't work. Images are always bad orientated. If you take a picture in Portrait mod, it will be displayed in Landscape mod.
Can you test on Sony Devices ?

**Comment by coomar2841** [comment]
Can you check how the images are being stored in the file system? ie, if they are stored in portrait or landscape mode?

**Comment by CorentinPacaud** [comment]
They 're all stored as landscape. Sony Xperia stores all pictures like this :
W x H (like1920x1080) and add exif rotation.

**Comment by xHunter** [comment]
@CorentinPacaud the change in the code only sets the orientation as the original orientation. 
Are you decoding the file to a bitmap?

**Comment by CorentinPacaud** [comment]
Yes I decode the file as Bitmap, but Glide does it and Glide read the exif data if they're here. I assume that you don't copy exit of the original file to the resize one, right ?

**Comment by xHunter** [comment]
It writes the exif tag for orientation in the resized one, It's working on me on Samsung phones.

**Comment by usmaanz** [comment]
I believe the workaround is not to specify a `maximumSize` against the picker but to always chose the `chosenImage.getThumbnail()' instead.

That's what i'm doing and from a quick test, it seems to be working as expected. It maintains the orientation.

**Comment by CorentinPacaud** [comment]
@usmaanz That's not what I want. I want the user to be able to take a photo, resize it and send it to a server. So I don't need a 4k photo, just a 1920x1920 maximum. So I set the maximum size of the photo to 1920....

**Comment by usmaanz** [comment]
@CorentinPacaud Fair enough. My above comment satisfies my needs but unfortunately doesn't seem to solve your issue. Hopefully @coomar2841 can get a fix in soon.

**Comment by CorentinPacaud** [comment]
@coomar2841 ping

**Comment by coomar2841** [comment]
Created #34 Please follow that thread for bugs related to exif data.

**Pull request merged**
